fx_version("cerulean")
game("common")
version("2.0.0")
author("Cfx.re <root@cfx.re> - Refactor Bitpredator")
description("A basic freeroam gametype that uses the default spawn logic from spawnmanager.")
repository("https://github.com/bitpredator/cfx-server-data")
resource_type("gametype")({ name = "Freeroam" })
client_script("basic_client.lua")
