fx_version("cerulean")
game("gta5")
version("2.0.0")
description("An example money system client.")
author("Cfx.re <root@cfx.re> Refactor Bitpredator")
repository("https://github.com/citizenfx/cfx-server-data")
client_script("client.lua")
server_script("server.lua")
lua53("yes")
