fx_version 'cerulean'
game 'common'
version '2.0.0'
author 'Cfx.re <root@cfx.re>'
description 'Builds resources with yarn. To learn more: https://classic.yarnpkg.com'
repository 'https://github.com/citizenfx/cfx-server-data'
server_script 'yarn_builder.js'
